### PR TITLE
Feat/add main

### PR DESCRIPTION
**Pull request by alfredobs97**
Hi! First of all, your package is amazing!!

In this PR, I tried to cache the original main file to prevent to be deleted when you clean lib folder.

### CODE REVIEW

**Comment by pbissonho** [comment]
Hello @alfredobs97
I really appreciate your contribution!

Normally when we create a new Flutter project, we replace that original main file with our main own file. 
It is possible to configure a template to generate only a "main.dart" file containing the desired code, so keeping that original main file that we don't normally use may not be a good thing.

What do you think about passing an flag argument to inform whether "main.file" should be maintained or not?

For example:

<plugin_name> create   --name <app_name>  --scaffold <scaffold_name> --keepMain

Applied in a plugin:

mvc create --name myapp --scaffold mvc --keepMain

In the code it would look something like this:

```dart
   .
   .
   .
  FlutterCreaterComand(this.scaffoldsPath) {
    argParser.addOption('name', abbr: 'n', help: 'Project name.');
    argParser.addOption('scaffold', abbr: 's', help: 'Scaffold template name.');
    argParser.addOption('description', abbr: 'd', help: 'Project descritiopn.');
    argParser.addFlag('kotlin', abbr: 'a', help: 'User kotlin.');
    argParser.addFlag('swift', abbr: 'i', help: 'User Swift.');
    argParser.addFlag('androidx', abbr: 'x', help: 'Use AndroidX.');
    argParser.addFlag('keepMain', abbr: 'k', help: 'Kepp main file.');
  }

  @override
  Future<void> run() async {
    var appName = argResults['name'];
    var scaffoldName = argResults['scaffold'];
    var description = argResults['description'];
    var useKotlin = argResults.wasParsed('kotlin');
    var useSwift = argResults.wasParsed('swift');
    var useAndroidX = argResults.wasParsed('androidx');
    var keepMain = argResults.wasParsed('keepMain');

    if (keepMain) {
      //... Lines required to maintain the main file
      //...
    }
   .
   .
```

**Comment by alfredobs97** [comment]
Done! Could you test it? I cannot find how to test your CLI @pbissonho

**Comment by pbissonho** [comment]
@alfredobs97 

From what I saw it was missing to add the flag: argParser.addFlag('keep-main', abbr: 'k', help: 'Keep main file.');

It should look like this:
```dart
   .
   .
   .
  FlutterCreaterComand(this.scaffoldsPath) {
    argParser.addOption('name', abbr: 'n', help: 'Project name.');
    argParser.addOption('scaffold', abbr: 's', help: 'Scaffold template name.');
    argParser.addOption('description', abbr: 'd', help: 'Project descritiopn.');
    argParser.addFlag('kotlin', abbr: 'a', help: 'User kotlin.');
    argParser.addFlag('swift', abbr: 'i', help: 'User Swift.');
    argParser.addFlag('androidx', abbr: 'x', help: 'Use AndroidX.');
    argParser.addFlag('keep-main', abbr: 'k', help: 'Keep main file.');
  }
```



To test you can create a unit test or activate the package directly from a path.

By unit test it would be something like:
```dart
  test('shoud create a tamplate - FAST CLI', () async {
    var commandRunner = CommandRunner('Fast CLI', 'An incredible Dart CLI.');
    var fastzCLI = FastCLI(commandRunner, PluginStorage());
    await fastzCLI.setupCommandRunner('mvc');
    await fastzCLI.run(
        ['fast', 'cli', 'mvc', 'controller', '--name', 'myController'], true);
  });
```
Activating globally and testing directly by cmd.

pub global activate --source path <pachage_path>

Example:  pub global activate --source path /home/pedro/documents/fast.cli/

You don't have to worry about writing the tests for this use case, the project tests are a bit messy, 
Intending to organize and refactor the tests in the coming weeks.

**Comment by pbissonho** [comment]
PR https://github.com/pbissonho/fast.cli/pull/6.

**Pull request closed without merging**
